erDiagram
    LØNNSMOTTAKER {
        DECIMAL LØPENR PK
        VARCHAR FØDSELSNR
        VARCHAR FORNAVN
        VARCHAR ETTERNAVN
    }
    UTBETALING {
        DECIMAL BELØP
        DATE DATO
        VARCHAR MOTTAKER_LØPENR FK
    }
    LØNNSMOTTAKER ||--o{ UTBETALING : "har"
