using NLog;
using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace WindowsDb2Editor.Services.AI.Export;

/// <summary>
/// Service for exporting AI analysis context to markdown files.
/// </summary>
public class AiExportService
{
    private static readonly Logger Logger = LogManager.GetCurrentClassLogger();
    
    /// <summary>
    /// Export AI context to markdown file.
    /// </summary>
    public async Task<string> ExportToMarkdownAsync(string content, string title, string? outputPath = null)
    {
        Logger.Info("Exporting AI context to markdown: {Title}", title);
        
        // Generate filename if not provided
        if (string.IsNullOrWhiteSpace(outputPath))
        {
            var timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
            var safeTitle = SanitizeFileName(title);
            var fileName = $"AI_Context_{safeTitle}_{timestamp}.md";
            outputPath = Path.Combine(Path.GetTempPath(), "WindowsDb2Editor", "AI_Exports", fileName);
        }
        
        // Ensure directory exists
        var directory = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrWhiteSpace(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
            Logger.Debug("Created export directory: {Directory}", directory);
        }
        
        // Build markdown content with metadata
        var markdown = new StringBuilder();
        
        // Frontmatter (for tools like Obsidian)
        markdown.AppendLine("---");
        markdown.AppendLine($"title: {title}");
        markdown.AppendLine($"generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        markdown.AppendLine($"tool: WindowsDb2Editor AI Assistant");
        markdown.AppendLine("---");
        markdown.AppendLine();
        
        // Content
        markdown.AppendLine(content);
        
        // Footer
        markdown.AppendLine();
        markdown.AppendLine("---");
        markdown.AppendLine();
        markdown.AppendLine("*Generated by WindowsDb2Editor AI Assistant*");
        markdown.AppendLine($"*Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}*");
        
        // Write to file
        await File.WriteAllTextAsync(outputPath, markdown.ToString(), Encoding.UTF8);
        
        Logger.Info("Exported AI context to: {Path} ({Size} bytes)", outputPath, new FileInfo(outputPath).Length);
        return outputPath;
    }
    
    /// <summary>
    /// Export Mermaid diagram with markdown context.
    /// </summary>
    public async Task<string> ExportMermaidWithContextAsync(string mermaidDiagram, string contextMarkdown, string title, string? outputPath = null)
    {
        Logger.Info("Exporting Mermaid diagram with context: {Title}", title);
        
        var content = new StringBuilder();
        
        // Context first
        content.AppendLine(contextMarkdown);
        content.AppendLine();
        
        // Mermaid diagram (properly embedded)
        content.AppendLine("## Complete Mermaid Diagram");
        content.AppendLine();
        content.AppendLine("```mermaid");
        content.AppendLine(mermaidDiagram);
        content.AppendLine("```");
        content.AppendLine();
        
        // Also save standalone .mmd file
        if (string.IsNullOrWhiteSpace(outputPath))
        {
            var timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
            var safeTitle = SanitizeFileName(title);
            outputPath = Path.Combine(Path.GetTempPath(), "WindowsDb2Editor", "AI_Exports", $"Mermaid_{safeTitle}_{timestamp}.md");
        }
        
        var mdPath = await ExportToMarkdownAsync(content.ToString(), title, outputPath);
        
        // Also save standalone .mmd file
        var mmdPath = Path.ChangeExtension(mdPath, ".mmd");
        await File.WriteAllTextAsync(mmdPath, mermaidDiagram, Encoding.UTF8);
        Logger.Info("Saved standalone Mermaid file: {Path}", mmdPath);
        
        return mdPath;
    }
    
    /// <summary>
    /// Export SQL CREATE statements.
    /// </summary>
    public async Task<string> ExportSqlAsync(string sql, string title, string? outputPath = null)
    {
        Logger.Info("Exporting SQL: {Title}", title);
        
        if (string.IsNullOrWhiteSpace(outputPath))
        {
            var timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
            var safeTitle = SanitizeFileName(title);
            var fileName = $"SQL_{safeTitle}_{timestamp}.sql";
            outputPath = Path.Combine(Path.GetTempPath(), "WindowsDb2Editor", "AI_Exports", fileName);
        }
        
        var directory = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrWhiteSpace(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }
        
        var content = new StringBuilder();
        content.AppendLine($"-- {title}");
        content.AppendLine($"-- Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        content.AppendLine($"-- Tool: WindowsDb2Editor");
        content.AppendLine();
        content.AppendLine(sql);
        
        await File.WriteAllTextAsync(outputPath, content.ToString(), Encoding.UTF8);
        
        Logger.Info("Exported SQL to: {Path}", outputPath);
        return outputPath;
    }
    
    /// <summary>
    /// Sanitize filename to remove invalid characters.
    /// </summary>
    private string SanitizeFileName(string fileName)
    {
        var invalid = Path.GetInvalidFileNameChars();
        var sanitized = new StringBuilder();
        
        foreach (var c in fileName)
        {
            if (Array.IndexOf(invalid, c) >= 0)
            {
                sanitized.Append('_');
            }
            else
            {
                sanitized.Append(c);
            }
        }
        
        var result = sanitized.ToString();
        
        // Limit length
        if (result.Length > 50)
        {
            result = result.Substring(0, 50);
        }
        
        return result;
    }
}

